### ISSUE TITLE
Calling getDomains on AdminContext throws error

### ISSUE THREAD

**Issue by mve** [mvdgeijn/directadmin#1]
Im connecting as an admin and trying to call getDomains but i'm getting the following error:

This code throws an error:
```
self::$adminContext = DirectAdmin::connectAdmin(
            "https://directadminserver.domain",
            $username,
            $password
        );

        $domains = self::$adminContext->getDomains();
```

```
Declaration of Mvdgeijn\DirectAdmin\Objects\Users\Admin::impersonate() must be compatible with Mvdgeijn\DirectAdmin\Objects\Users\Reseller::impersonate(): Mvdgeijn\DirectAdmin\Context\ResellerContext

  at vendor/mvdgeijn/directadmin/src/DirectAdmin/Objects/Users/Admin.php:35
     31▕ 
     32▕     /**
     33▕      * @return AdminContext
     34▕      */
  ➜  35▕     public function impersonate()
     36▕     {
     37▕         /** @var AdminContext $context */
     38▕         if (!($context = $this->getContext()) instanceof AdminContext) {
     39▕             throw new DirectAdminException('You need to be an admin to impersonate another admin');

      +9 vendor frames 
  10  app/Commands/CommandName.php:82
      Mvdgeijn\DirectAdmin\Context\AdminContext::getDomains()
```

If I connect as an admin and then first get a user and do getDomains on that user I do get the domains for that user.
This code works. Only difference is the getUser.
```
self::$adminContext = DirectAdmin::connectAdmin(
            "https://directadminserver.domain",
            $username,
            $password
        );

        $domains = self::$adminContext->getUser('someuser')->getDomains();
```

Seems like it shouldn't even be possible to get the domains on a context directly but this is passed on through inheritance.
<img width="726" alt="Scherm­afbeelding 2023-08-07 om 13 52 01" src="https://github.com/mvdgeijn/directadmin/assets/38584349/8a5864cb-d3fe-4056-9e17-ae340fba6549">

**Comment by mvdgeijn** [comment]
In release v0.12.1 this problem is fixed.

**Comment by mvdgeijn** [comment]
If I remember correctly, in the admin context you get all domains from all resellers and users. On reseller level you get all domains from that reseller and the users connected to that reseller.
