### ISSUE TITLE
Fetch Mailbox by address?

### ISSUE THREAD

**Issue by RM6SS62** [mvdgeijn/directadmin#2]
Hi, I was investigating the source and I don't see a way to get reference to an specific email box, so for example if I want to delete on of them I have to iterate over the full set.

Am I missing something and this is already implemented?

Thanks in advance.

**Comment by mvdgeijn** [comment]
Hi,

If $da contains the correct UserContext object, you can do the following:

```
$daDomain = $da->getDomain($domainName);
(new Mailbox($mailbox, $daDomain))->delete();
```

$mailbox only needs to contain the left part of the e-mail address (e.g. test in case the mailbox you want to delete is test@example.com)

**Comment by RM6SS62** [comment]
Perfect! Thank you very much, looking forward too see the client expanded!
